# -*- coding: utf-8 -*-
"""Codingan Model SEIR_662023007.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/145t6p-iPFQcd80LZ5kAxABv_T4pL5bZh
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

# Parameter SEIR
N = 1000        # Total populasi
beta = 0.3      # Laju transmisi
sigma = 0.2     # Masa inkubasi
gamma = 0.1     # Laju pemulihan

# Kondisi awal
S0 = 990    # Rentan
E0 = 7      # Terpapar
I0 = 2      # Infeksi
R0 = 1      # Sembuh

# Sistem persamaan diferensial
def seir_model(y, t, N, beta, sigma, gamma):
    S, E, I, R = y
    dSdt = -beta * S * I / N
    dEdt = beta * S * I / N - sigma * E
    dIdt = sigma * E - gamma * I
    dRdt = gamma * I
    return [dSdt, dEdt, dIdt, dRdt]

# Waktu simulasi (dalam hari)
t = np.linspace(0, 160, 160)

# Solusi ODE
sol = odeint(seir_model, [S0, E0, I0, R0], t, args=(N, beta, sigma, gamma))
S, E, I, R = sol.T

# Plot hasil simulasi
plt.figure(figsize=(10, 6))
plt.plot(t, S, label='Susceptible', color='blue')
plt.plot(t, E, label='Exposed', color='yellow')
plt.plot(t, I, label='Infectious', color='red')
plt.plot(t, R, label='Recovered', color='green')
plt.xlabel('Waktu (hari)')
plt.ylabel('Jumlah Individu')
plt.title('Simulasi Model SEIR')
plt.legend()
plt.grid()
plt.show()