# -*- coding: utf-8 -*-
"""Model SIR dengan kelahiran & kematian

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11V8GHbFx_vI9CTReEbE1xX4zuSVsObZq
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint

# Parameter model
beta = 0.2    #Laju infeksi
gamma = 0.1   #Laju pemulihan
N = 1000      #Total Populasi
alpha = 0.02  #Laju kelahiran
sigma = 0.01  #Laju kematian

#Kondisi awal
S0 = N - 1
I0 = 1
R0 = 0

t = np.linspace(0, 160, 160)  #Simulasi selama 160 hari

#Model SIR
def sir_model(y, t, N, beta, gamma, alpha, sigma):
    S, I, R = y

    dSdt = alpha * N - (beta * S * I / N) - sigma * S
    dIdt = (beta * S * I / N) - gamma * I - sigma * I
    dRdt = gamma * I - sigma * R

    return [dSdt, dIdt, dRdt]

#Menyelesaikan sistem persamaan diferensial
y0 = [S0, I0, R0]
solution = odeint(sir_model, y0, t, args=(N, beta, gamma, alpha, sigma))
S, I, R = solution.T

# Plot hasil
plt.figure(figsize=(10, 6))
plt.plot(t, S, label='Susceptible', color='blue')
plt.plot(t, I, label='Infected', color='red')
plt.plot(t, R, label='Recovered', color='green')
plt.xlabel('Waktu (hari)')
plt.ylabel('Jumlah Individu')
plt.title('Simulasi Model SIR dengan Kelahiran dan Kematian')
plt.legend()
plt.grid()
plt.show()