# -*- coding: utf-8 -*-
"""Nilai Eigen 662023007

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17CvfOig8NgQeqX2X1r6E4MZLurvrbwdm
"""

import numpy as lnx

A = lnx.array([[4, 1],
              [-2, 3]])
nilaieigen, vektoreigen = lnx.linalg.eig(A)
print("nilaieigen:")
print(nilaieigen)
print("\nvektoreigen:")
print(vektoreigen)

import numpy as lnx
A = lnx.array([[7, 4],
              [2, 2]])
nilaieigen, vektoreigen = lnx.linalg.eig(A)
print("nilaieigen:")
print(nilaieigen)
print("\nvektoreigen:")
print(vektoreigen)

import numpy as lnx
A = lnx.array([[7, 4],
              [2, 2]])
nilaieigen, vektoreigen = lnx.linalg.eig(A)
print("nilaieigen:")
print(nilaieigen)
print("\nvektoreigen:")
print(vektoreigen)