# -*- coding: utf-8 -*-
"""Penurunan suhu kopi_662023007

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Aq6Y3q-C0YEUmUFkQOmMjR7n4HtYTAy6
"""

#import pustaka yang diperlukan
import numpy as np
import matplotlib.pyplot as plt

def   Perubahan_pada_suhu_Kopi(Ta, T0, t, k):
  """
  Menyelesaikan T(t) = Ta + e^(-k * t) * T0

  Parameter:
    t  : array-like, waktu
    Ta : float, suhu ruangan
    T0 : float, suhu awal
    k  : float, konstanta laju pendinginan

  Mengembalikan:
  T : array-like, suhu
  """
  return Ta + np.exp(-k * t) * T0

#Parameter contoh
Ta = 22
T0 = 90
k  = 0.07
t  = np.linspace(0, 100, 200)

#Menyelesaikan persamaan
T = Perubahan_pada_suhu_Kopi(Ta, T0, t, k)

#Plot hasilnya
plt.figure(figsize=(8,6))
plt.plot(t, T, label=f"T(t) = {Ta} + exp(-{k} * t) * {T0}", color="purple")
plt.title("Perubahan Suhu Kopi Karena Pengaruh Suhu Ruang")
plt.xlabel("Waktu (t)")
plt.ylabel("Suhu (T)")
plt.legend()
plt.grid()
plt.show()