# -*- coding: utf-8 -*-
"""Pertumbuhan logistik_662023007

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jflsLhGMpPJ5ju6MQh8nDwBPhoWBY5fk
"""

#Import pustaka yang diperlukan
import numpy as np
import matplotlib.pyplot as plt

#Fungsi untuk menyelesaikan persamaan diferensial secara analitik
def pertumbuhan_logistik(K, t, r, X0):
  """
  Menyelesaikan N(t) = (K * X0 * e^(r * t))/(K + X0 * (e^(r * t) - 1))

  Parameter:
    t : array-like, waktu
    K : float, konstanta
    r : float, tingkat pertumbuhan
    X0 : float, populasi awal

  Mengembalikan:
  N : array-like, populasi pada setiap titik waktu
  """
  return (K * X0 * np.exp(r * t)) / (K + X0 * (np.exp(r * t) - 1))

#Parameter contoh
X0 = 50
K = 200
r = 0.5
t = np.linspace(0, 13)
#Menyelesaikan persamaan
N = pertumbuhan_logistik(K, t, r, X0)

#Plot hasilnya
plt.figure(figsize=(8,6))
plt.plot(t, N, label=f"(K * X0 * e^(r * t))/(K + X0 * (e^(r * t) - 1))")
plt.title("Pertumbuhan Logistik pada ikan kolam")
plt.xlabel("Waktu (t)")
plt.ylabel("Populasi (P)")
plt.legend()
plt.grid()
plt.show()